use crate::config::QualityConfig;
use serde::Serialize;
use std::path::Path;

#[derive(Debug, Serialize, Clone)]
pub struct QualityFinding {
    pub kind: String,
    pub category: String,
    pub kill_rate: Option<f64>,
    pub threshold: Option<f64>,
    pub suggested_action: String,
    pub playbook_command: String,
    pub message: String,
}

impl QualityFinding {
    pub fn for_test_type(test_type: &str) -> Self {
        Self {
            kind: format!("quality-{test_type}"),
            category: "quality".to_string(),
            kill_rate: None,
            threshold: None,
            suggested_action: "enable_capability".to_string(),
            playbook_command: format!("ah explain quality-{test_type}"),
            message: format!("{test_type} tests ran successfully"),
        }
    }
}

impl PartialEq for QualityFinding {
    fn eq(&self, other: &Self) -> bool {
        self.kind == other.kind
            && self.category == other.category
            && self.kill_rate.map(f64::to_bits) == other.kill_rate.map(f64::to_bits)
            && self.threshold.map(f64::to_bits) == other.threshold.map(f64::to_bits)
            && self.suggested_action == other.suggested_action
            && self.playbook_command == other.playbook_command
            && self.message == other.message
    }
}

impl Eq for QualityFinding {}

pub fn collect_quality_findings(
    repo_root: &Path,
    config: &QualityConfig,
    scope: &str,
) -> (Vec<QualityFinding>, Vec<String>) {
    let mut findings = Vec::new();
    let mut tool_errors = Vec::new();
    if let Some(mutation) = &config.mutation {
        if mutation.enabled {
            match mutation_finding(repo_root, mutation, scope) {
                Ok(Some(finding)) => findings.push(finding),
                Ok(None) => {}
                Err(msg) => tool_errors.push(msg),
            }
        }
    }
    (findings, tool_errors)
}

fn mutation_finding(
    repo_root: &Path,
    mutation: &crate::config::MutationConfig,
    scope: &str,
) -> Result<Option<QualityFinding>, String> {
    if scope == "pre-commit" {
        return Ok(None);
    }
    match run_mutation_tool(repo_root, mutation) {
        Ok(None) => Ok(None),
        Ok(Some(kill_rate)) => {
            if kill_rate >= mutation.threshold {
                return Ok(None);
            }
            Ok(Some(QualityFinding {
                kind: "quality-mutation".to_string(),
                category: "quality".to_string(),
                kill_rate: Some(kill_rate),
                threshold: Some(mutation.threshold),
                suggested_action: "enable_capability".to_string(),
                playbook_command: "ah explain enable_capability".to_string(),
                message: format!(
                    "mutation kill rate {:.0}% is below threshold {:.0}%",
                    kill_rate * 100.0,
                    mutation.threshold * 100.0
                ),
            }))
        }
        Err(msg) => Err(msg),
    }
}

fn run_mutation_tool(
    repo_root: &Path,
    mutation: &crate::config::MutationConfig,
) -> Result<Option<f64>, String> {
    if mutation.command.is_empty() {
        return Ok(None);
    }
    let (prog, args) = mutation
        .command
        .split_first()
        .ok_or_else(|| "mutation command is empty".to_string())?;

    // Replace "{}" placeholder with a generated runner script path.
    let args: Vec<String> = args
        .iter()
        .map(|arg| {
            if arg == "{}" {
                generate_runner_script(repo_root)
            } else {
                arg.clone()
            }
        })
        .collect();

    let output = std::process::Command::new(prog)
        .args(&args)
        .current_dir(repo_root)
        .output()
        .map_err(|e| format!("failed to spawn mutation tool: {e}"))?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(format!(
            "mutation tool exited non-zero ({}): {}",
            output.status.code().unwrap_or(-1),
            stderr.trim()
        ));
    }
    let stdout = std::str::from_utf8(&output.stdout)
        .map_err(|_| "mutation tool output is not UTF-8".to_string())?;
    let parsed: serde_json::Value = serde_json::from_str(stdout.trim())
        .map_err(|e| format!("mutation tool output is not valid JSON: {e}"))?;
    Ok(parsed["kill_rate"].as_f64())
}

fn generate_runner_script(repo_root: &Path) -> String {
    let dir = repo_root.join(".espectacular");
    let _ = std::fs::create_dir_all(&dir);
    let path = dir.join("mutation-runner.sh");
    // Generate a simple script that runs the project's tests.
    // The mutation tool uses this script to run tests and compute
    // the mutation score. The user can replace this with a custom
    // runner by pointing the command directly at their script.
    let _ = std::fs::write(
        &path,
        b"#!/bin/sh\n# Mutation test runner - generated by espectacular\n# Replace this file with a custom runner for your mutation tool.\necho '{\"kill_rate\": 0.0}'\n",
    );
    let _ = std::process::Command::new("chmod")
        .args(["+x", path.to_str().unwrap_or("")])
        .output();
    path.to_string_lossy().into_owned()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{MutationConfig, QualityConfig};
    use std::fs;

    fn mutation_command(dir: &std::path::Path, kill_rate: f64) -> Vec<String> {
        let script = dir.join("mutation-runner.sh");
        fs::write(
            &script,
            format!("printf '{{\"kill_rate\": {}}}'", kill_rate),
        )
        .unwrap();
        vec!["/bin/sh".to_string(), script.to_string_lossy().to_string()]
    }

    // 8.1 RED: mutation finding emitted when enabled and below threshold

    #[test]
    fn mutation_finding_emitted_when_below_threshold() {
        let dir = tempfile::tempdir().unwrap();
        let config = QualityConfig {
            mutation: Some(MutationConfig {
                enabled: true,
                threshold: 0.80,
                command: mutation_command(dir.path(), 0.60),
            }),
        };
        let (findings, _) = collect_quality_findings(dir.path(), &config, "full");
        assert_eq!(
            findings.len(),
            1,
            "expected exactly one quality_mutation finding"
        );
        let f = &findings[0];
        assert_eq!(f.kind, "quality-mutation");
        assert_eq!(f.category, "quality");
        assert!(f.kill_rate.is_some(), "kill_rate must be present");
    }

    #[test]
    fn mutation_finding_carries_kill_rate_and_threshold() {
        let dir = tempfile::tempdir().unwrap();
        let config = QualityConfig {
            mutation: Some(MutationConfig {
                enabled: true,
                threshold: 0.80,
                command: mutation_command(dir.path(), 0.60),
            }),
        };
        let (findings, _) = collect_quality_findings(dir.path(), &config, "full");
        let f = &findings[0];
        assert!((f.kill_rate.unwrap() - 0.60).abs() < 1e-9);
        assert!((f.threshold.unwrap() - 0.80).abs() < 1e-9);
    }

    #[test]
    fn mutation_finding_carries_suggested_action_and_playbook_command() {
        let dir = tempfile::tempdir().unwrap();
        let config = QualityConfig {
            mutation: Some(MutationConfig {
                enabled: true,
                threshold: 0.80,
                command: mutation_command(dir.path(), 0.50),
            }),
        };
        let (findings, _) = collect_quality_findings(dir.path(), &config, "full");
        let f = &findings[0];
        assert!(!f.suggested_action.is_empty());
        assert!(!f.playbook_command.is_empty());
    }

    #[test]
    fn no_mutation_finding_when_above_threshold() {
        let dir = tempfile::tempdir().unwrap();
        let config = QualityConfig {
            mutation: Some(MutationConfig {
                enabled: true,
                threshold: 0.80,
                command: mutation_command(dir.path(), 0.90),
            }),
        };
        let (findings, _) = collect_quality_findings(dir.path(), &config, "full");
        assert!(
            findings.is_empty(),
            "no finding expected when kill rate meets threshold"
        );
    }

    #[test]
    fn no_mutation_finding_when_disabled() {
        let dir = tempfile::tempdir().unwrap();
        let config = QualityConfig {
            mutation: Some(MutationConfig {
                enabled: false,
                threshold: 0.80,
                command: mutation_command(dir.path(), 0.50),
            }),
        };
        let (findings, _) = collect_quality_findings(dir.path(), &config, "full");
        assert!(
            findings.is_empty(),
            "disabled mutation must not emit finding"
        );
    }

    // 8.3 RED: mutation skipped in pre-commit scope

    #[test]
    fn mutation_skipped_in_precommit_scope() {
        let dir = tempfile::tempdir().unwrap();
        let config = QualityConfig {
            mutation: Some(MutationConfig {
                enabled: true,
                threshold: 0.80,
                command: mutation_command(dir.path(), 0.10),
            }),
        };
        let (findings, _) = collect_quality_findings(dir.path(), &config, "pre-commit");
        assert!(
            findings.is_empty(),
            "mutation must be skipped in pre-commit scope"
        );
    }

    #[test]
    fn mutation_findings_deterministically_ordered() {
        let dir = tempfile::tempdir().unwrap();
        let config = QualityConfig {
            mutation: Some(MutationConfig {
                enabled: true,
                threshold: 0.80,
                command: mutation_command(dir.path(), 0.60),
            }),
        };
        let (a, _) = collect_quality_findings(dir.path(), &config, "full");
        let (b, _) = collect_quality_findings(dir.path(), &config, "full");
        assert_eq!(a, b, "findings must be deterministic");
    }

    #[test]
    fn mutation_placeholder_replaced_with_runner_script() {
        let dir = tempfile::tempdir().unwrap();
        // Use the documented {} placeholder shape.
        let config = QualityConfig {
            mutation: Some(MutationConfig {
                enabled: true,
                threshold: 0.80,
                command: vec!["/bin/sh".to_string(), "{}".to_string()],
            }),
        };
        // The {} placeholder should be replaced with a generated runner script
        // that produces a kill rate below threshold, yielding a mutation finding.
        let (findings, _) = collect_quality_findings(dir.path(), &config, "full");
        assert_eq!(
            findings.len(),
            1,
            "expected exactly one quality_mutation finding with placeholder"
        );
        let f = &findings[0];
        assert_eq!(f.kind, "quality-mutation");
        assert!(f.kill_rate.is_some(), "kill_rate must be present");
    }
}
